/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	clustercidrv1 "sigs.k8s.io/node-ipam-controller/pkg/apis/clustercidr/v1"
)

// ClusterCIDRLister helps list ClusterCIDRs.
// All objects returned here must be treated as read-only.
type ClusterCIDRLister interface {
	// List lists all ClusterCIDRs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clustercidrv1.ClusterCIDR, err error)
	// Get retrieves the ClusterCIDR from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clustercidrv1.ClusterCIDR, error)
	ClusterCIDRListerExpansion
}

// clusterCIDRLister implements the ClusterCIDRLister interface.
type clusterCIDRLister struct {
	listers.ResourceIndexer[*clustercidrv1.ClusterCIDR]
}

// NewClusterCIDRLister returns a new ClusterCIDRLister.
func NewClusterCIDRLister(indexer cache.Indexer) ClusterCIDRLister {
	return &clusterCIDRLister{listers.New[*clustercidrv1.ClusterCIDR](indexer, clustercidrv1.Resource("clustercidr"))}
}
