/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1 "sigs.k8s.io/node-ipam-controller/pkg/apis/clustercidr/v1"
	clustercidrv1 "sigs.k8s.io/node-ipam-controller/pkg/client/clientset/versioned/typed/clustercidr/v1"
)

// fakeClusterCIDRs implements ClusterCIDRInterface
type fakeClusterCIDRs struct {
	*gentype.FakeClientWithList[*v1.ClusterCIDR, *v1.ClusterCIDRList]
	Fake *FakeNetworkingV1
}

func newFakeClusterCIDRs(fake *FakeNetworkingV1) clustercidrv1.ClusterCIDRInterface {
	return &fakeClusterCIDRs{
		gentype.NewFakeClientWithList[*v1.ClusterCIDR, *v1.ClusterCIDRList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("clustercidrs"),
			v1.SchemeGroupVersion.WithKind("ClusterCIDR"),
			func() *v1.ClusterCIDR { return &v1.ClusterCIDR{} },
			func() *v1.ClusterCIDRList { return &v1.ClusterCIDRList{} },
			func(dst, src *v1.ClusterCIDRList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ClusterCIDRList) []*v1.ClusterCIDR { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ClusterCIDRList, items []*v1.ClusterCIDR) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
