// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	clustercidrv1 "github.com/mneverov/cluster-cidr-controller/pkg/apis/clustercidr/v1"
	versioned "github.com/mneverov/cluster-cidr-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/mneverov/cluster-cidr-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/mneverov/cluster-cidr-controller/pkg/client/listers/clustercidr/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterCIDRInformer provides access to a shared informer and lister for
// ClusterCIDRs.
type ClusterCIDRInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ClusterCIDRLister
}

type clusterCIDRInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterCIDRInformer constructs a new informer for ClusterCIDR type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterCIDRInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterCIDRInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterCIDRInformer constructs a new informer for ClusterCIDR type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterCIDRInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1().ClusterCIDRs().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1().ClusterCIDRs().Watch(context.TODO(), options)
			},
		},
		&clustercidrv1.ClusterCIDR{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterCIDRInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterCIDRInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterCIDRInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clustercidrv1.ClusterCIDR{}, f.defaultInformer)
}

func (f *clusterCIDRInformer) Lister() v1.ClusterCIDRLister {
	return v1.NewClusterCIDRLister(f.Informer().GetIndexer())
}
