// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/mneverov/cluster-cidr-controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ClusterCIDRs returns a ClusterCIDRInformer.
	ClusterCIDRs() ClusterCIDRInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ClusterCIDRs returns a ClusterCIDRInformer.
func (v *version) ClusterCIDRs() ClusterCIDRInformer {
	return &clusterCIDRInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
